# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 7

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

skip_tags: true

build: off

test_script:
  - node --version && npm --version
  - npm test